# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Workout.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from search_win import Ui_Home3


class Ui_Home(object):

    def openWindow(self):

        self.window1 = QtWidgets.QMainWindow()

        self.ui = Ui_Home3()

        self.ui.setupUi(self.window1)

        self.window1.show()


    def press_it_pushup(self):
        file1 = open('choice.txt', 'w')
        file1.write("1")

    def press_it_Squats(self):
        file1 = open('choice.txt', 'w')
        file1.write("2")

    def press_it_dumbelcurls(self):
        file1 = open('choice.txt', 'w')
        file1.write("3")

    def press_it_latpulls(self):
        file1 = open('choice.txt', 'w')
        file1.write("4")

    def press_it_seated(self):
        file1 = open('choice.txt', 'w')
        file1.write("5")


    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(1200, 550)
        self.centralwidget = QtWidgets.QWidget(Home)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, -30, 1231, 850))
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(-30, 70, 591, 451))
        self.widget_2.setStyleSheet("border-image: url(:/images/gymlogo3.jpg);")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(530, 60, 571, 81))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(255, 0, 0);\n"
"font: 63 26pt \"Segoe UI Variable Text Semibold\";\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(510, 260, 291, 61))
        self.pushButton.setStyleSheet("font: 63 18pt \"Segoe UI Variable Text Semibold\";\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0.818, x2:1, y2:1, stop:0 rgba(206, 24, 56, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        ########################
        self.pushButton.clicked.connect(self.openWindow)
        self.pushButton.clicked.connect(Home.close)
        self.pushButton.clicked.connect(self.press_it_pushup)
        ########################
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(850, 260, 291, 61))
        self.pushButton_3.setStyleSheet("font: 63 18pt \"Segoe UI Variable Text Semibold\";\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0.818, x2:1, y2:1, stop:0 rgba(206, 24, 56, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        ########################
        self.pushButton_3.clicked.connect(self.openWindow)
        self.pushButton_3.clicked.connect(Home.close)
        self.pushButton_3.clicked.connect(self.press_it_Squats)
        #########################
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(680, 460, 291, 61))
        self.pushButton_4.setStyleSheet("font: 63 18pt \"Segoe UI Variable Text Semibold\";\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0.818, x2:1, y2:1, stop:0 rgba(206, 24, 56, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        ########################
        self.pushButton_4.clicked.connect(self.openWindow)
        self.pushButton_4.clicked.connect(Home.close)
        self.pushButton_4.clicked.connect(self.press_it_seated)
        #########################
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(850, 360, 291, 61))
        self.pushButton_5.setStyleSheet("font: 63 18pt \"Segoe UI Variable Text Semibold\";\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0.818, x2:1, y2:1, stop:0 rgba(206, 24, 56, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        ########################
        self.pushButton_5.clicked.connect(self.openWindow)
        self.pushButton_5.clicked.connect(Home.close)
        self.pushButton_5.clicked.connect(self.press_it_latpulls)
        #########################
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setGeometry(QtCore.QRect(510, 360, 291, 61))
        self.pushButton_6.setStyleSheet("font: 63 18pt \"Segoe UI Variable Text Semibold\";\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0.818, x2:1, y2:1, stop:0 rgba(206, 24, 56, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 255, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        ########################
        self.pushButton_6.clicked.connect(self.openWindow)
        self.pushButton_6.clicked.connect(Home.close)
        self.pushButton_6.clicked.connect(self.press_it_dumbelcurls)
        #########################
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(570, 160, 471, 41))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(255, 0, 0);\n"
"font: 63 22pt \"Segoe UI Variable Text Semibold\";")
        self.label_2.setObjectName("label_2")
        Home.setCentralWidget(self.centralwidget)

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "MainWindow"))
        self.label.setText(_translate("Home", "Home Workout Monitoring "))
        self.pushButton.setText(_translate("Home", "Push Ups"))
        self.pushButton_3.setText(_translate("Home", "Squats"))
        self.pushButton_4.setText(_translate("Home", "Seated Cabel Rows"))
        self.pushButton_5.setText(_translate("Home", "Lat Pulldown"))
        self.pushButton_6.setText(_translate("Home", "Dumbell Curls"))
        self.label_2.setText(_translate("Home", "Choose the desired workout"))
import res_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Home = QtWidgets.QMainWindow()
    ui = Ui_Home()
    ui.setupUi(Home)
    Home.show()
    sys.exit(app.exec_())
