# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from secwindow import Ui_MainWindow
import sys
from PyQt5.QtCore import QUrl



class Ui_Home3(QtWidgets.QMainWindow):

    def openWindow1(self):

        self.window1 = QtWidgets.QMainWindow()

        self.ui = Ui_MainWindow()

        self.ui.setupUi(self.window1)

        self.window1.show()

    def openWindow2(self):
        from mainwindow import Ui_Home

        self.window2 = QtWidgets.QMainWindow()

        self.ui = Ui_Home()

        self.ui.setupUi(self.window2)

        self.window2.show()

    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(1200, 550)
        self.centralwidget = QtWidgets.QWidget(Home)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, -30, 1231, 850))
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(-30, 70, 591, 451))
        self.widget_2.setStyleSheet("border-image: url(:/images/gymlogo3.jpg);")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(530, 60, 571, 81))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(255, 0, 0);\n"
"font: 63 26pt \"Segoe UI Variable Text Semibold\";\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(670, 290, 291, 61))
        self.pushButton.setStyleSheet("font: 63 18pt \"Segoe UI Variable Text Semibold\";\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0.818, x2:1, y2:1, stop:0 rgba(206, 24, 56, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.get_vid_file)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(660, 180, 301, 41))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(255, 0, 0);\n"
"font: 63 22pt \"Segoe UI Variable Text Semibold\";")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(670, 380, 291, 61))
        self.pushButton_2.setStyleSheet("font: 63 18pt \"Segoe UI Variable Text Semibold\";\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0.818, x2:1, y2:1, stop:0 rgba(206, 24, 56, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_2.clicked.connect(self.openWindow1)
        self.pushButton_2.clicked.connect(Home.close)

        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(670, 470, 291, 61))
        self.pushButton_3.setStyleSheet("font: 63 18pt \"Segoe UI Variable Text Semibold\";\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0.818, x2:1, y2:1, stop:0 rgba(206, 24, 56, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.openWindow2)
        self.pushButton_3.clicked.connect(Home.close)
        Home.setCentralWidget(self.centralwidget)

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "MainWindow"))
        self.label.setText(_translate("Home", "Home Workout Monitoring "))
        self.pushButton.setText(_translate("Home", "Search"))
        self.label_2.setText(_translate("Home", "Choose the video "))
        self.pushButton_2.setText(_translate("Home", "Next"))
        self.pushButton_3.setText(_translate("Home", "back"))

    def get_vid_file(self):
        vid, _ = QtWidgets.QFileDialog.getOpenFileName(self, "Open Video", "~", "Video Files (*.mp4)")
        url_com = QUrl.fromLocalFile(vid)
        QUrl(url_com).toLocalFile()
        file1 = open('url.txt', 'w')
        file1.write(QUrl(url_com).toLocalFile())
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Home = QtWidgets.QMainWindow()
    ui = Ui_Home3()
    ui.setupUi(Home)
    Home.show()
    sys.exit(app.exec_())
